name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install additional targets
        run: |
          rustup target add x86_64-pc-windows-gnu
          rustup target add i686-pc-windows-gnu

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full build-essential pkg-config \
              libusb-dev libusb-1.0 dfu-util fwupd gcc-mingw-w64-x86-64 \
              gcc-mingw-w64-i686 gcc-arm-none-eabi

      - name: Download libusb DLLs for Windows
        working-directory: software
        run: |
          wget https://github.com/libusb/libusb/releases/download/v1.0.23/libusb-1.0.23.7z
          mkdir libusb
          mv libusb-1.0.23.7z libusb/
          cd libusb
          7z x libusb-1.0.23.7z

      - name: Build for Linux x86_64
        working-directory: software
        run: |
          cargo clean
          cargo build --release
          cp target/release/ecpdap ecpdap_linux_x86_64

      - name: Build for Windows x86_64
        working-directory: software
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
          RUSTFLAGS: -L ${{ github.workspace }}/software/libusb/MinGW64/dll/
        run: |
          cargo clean
          cargo build --release --target x86_64-pc-windows-gnu
          cp target/x86_64-pc-windows-gnu/release/ecpdap.exe ecpdap_windows_x86_64.exe

      - name: Build for Windows i686
        working-directory: software
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
          RUSTFLAGS: -L ${{ github.workspace }}/software/libusb/MinGW32/dll/ -C panic=abort
        run: |
          cargo clean
          cargo build --release --target i686-pc-windows-gnu
          cp target/i686-pc-windows-gnu/release/ecpdap.exe ecpdap_windows_i686.exe

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
          body: |
            The following pre-built files are available:
              * `ecpdap_linux_x86_64`: ecpdap control software for Linux (64-bit)
              * `ecpdap_windows_x86_64.exe`: ecpdap control software for Windows (64-bit)
              * `ecpdap_windows_i686.exe`: ecpdap control software for Windows (32-bit)

            ecpdap requires libusb be installed; on Linux it should suffice to install libusb-1.0, on Windows download the pre-built DLLs from [libusb.info](https://libusb.info/) and either install them system-wide or put them in the same directory as your executable.

      - name: Upload ecpdap for Linux x86_64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: software/ecpdap_linux_x86_64
          asset_name: ecpdap_linux_x86_64
          asset_content_type: application/octet-stream

      - name: Upload ecpdap for Windows x86_64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: software/ecpdap_windows_x86_64.exe
          asset_name: ecpdap_windows_x86_64.exe
          asset_content_type: application/octet-stream

      - name: Upload ecpdap for Windows i686
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: software/ecpdap_windows_i686.exe
          asset_name: ecpdap_windows_i686.exe
          asset_content_type: application/octet-stream
